version: "3.7"
services:
  go-monitor:
    image: ghcr.io/${GITHUB_ACTOR}/${PROJECT_NAME}:latest
    container_name: fiber-app
    ports:
      - "${FIBER_PORT}:${FIBER_PORT}" # FIBER_PORT 환경 변수 사용
    env_file:
      - .env
    networks:
      - app

networks:
  app:
    driver: bridge
